import { prisma } from './src/services/db';

async function checkEmbeddings() {
    console.log("Checking book chunks...");
    const chunk = await prisma.bookChunk.findFirst({
        select: { embedding: true, bookId: true }
    });

    if (!chunk) {
        console.log("No chunks found in database.");
        return;
    }

    try {
        const embedding = JSON.parse(chunk.embedding);
        console.log(`Checking embedding for book ${chunk.bookId}`);
        console.log(`First 5 values: ${embedding.slice(0, 5).join(', ')}`);

        // Check if values look like Math.random() (all positive, no negatives)
        const hasNegatives = embedding.some((n: number) => n < 0);

        if (!hasNegatives) {
            console.log("⚠️ WARNING: Embedding contains NO negative values.");
            console.log("This strongly suggests it was generated by Math.random() (Mock Fallback).");
            console.log("Real embeddings (like text-embedding-004) almost always contain negative values.");
        } else {
            console.log("✅ Embedding contains negative values. Likely real.");
        }

    } catch (e) {
        console.error("Error parsing embedding:", e);
    }
}

checkEmbeddings()
    .catch(console.error)
    .finally(() => prisma.$disconnect());
